language: node_js
dist: xenial

node_js:
  - '4'
  - '6'
  - '8'
  - '10'
  - '12'

script:
  - npm run-script test:ci

notifications:
  email:
    - travis@nodejitsu.com
  irc: "irc.freenode.org#nodejitsu"
